/**
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robots Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsModel#getCapability <em>Capability</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RobotsModel#getRobots <em>Robots</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsModel()
 * @model
 * @generated
 */
public interface RobotsModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Capability</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Capability}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capability</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsModel_Capability()
   * @model containment="true"
   * @generated
   */
  EList<Capability> getCapability();

  /**
   * Returns the value of the '<em><b>Robots</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Robot}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Robots</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRobotsModel_Robots()
   * @model containment="true"
   * @generated
   */
  EList<Robot> getRobots();

} // RobotsModel
