/*
 * generated by Xtext 2.26.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTasksModelAccess().getAlternatives(), "rule__TasksModel__Alternatives");
			builder.put(grammarAccess.getWorldModelAccess().getAlternatives(), "rule__WorldModel__Alternatives");
			builder.put(grammarAccess.getMissionAccess().getAlternatives(), "rule__Mission__Alternatives");
			builder.put(grammarAccess.getQoSAccess().getAlternatives(), "rule__QoS__Alternatives");
			builder.put(grammarAccess.getAllRobotsXXAccess().getCoordinateAlternatives_5_0(), "rule__AllRobotsXX__CoordinateAlternatives_5_0");
			builder.put(grammarAccess.getAllRobotsXAccess().getCoordinateAlternatives_2_0(), "rule__AllRobotsX__CoordinateAlternatives_2_0");
			builder.put(grammarAccess.getAllRobotsXAccess().getTypeAlternatives_3_0(), "rule__AllRobotsX__TypeAlternatives_3_0");
			builder.put(grammarAccess.getRobotsXXAccess().getCoordinateAlternatives_4_0(), "rule__RobotsXX__CoordinateAlternatives_4_0");
			builder.put(grammarAccess.getRobotsXAccess().getCoordinateAlternatives_4_0(), "rule__RobotsX__CoordinateAlternatives_4_0");
			builder.put(grammarAccess.getRobotsXAccess().getTypeAlternatives_5_0(), "rule__RobotsX__TypeAlternatives_5_0");
			builder.put(grammarAccess.getLocationOrSpaceAccess().getAlternatives(), "rule__LocationOrSpace__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getProblemSpecificationAccess().getGroup(), "rule__ProblemSpecification__Group__0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getGroup_18(), "rule__ProblemSpecification__Group_18__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup(), "rule__AtomicTask__Group__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup_6(), "rule__AtomicTask__Group_6__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup_7(), "rule__AtomicTask__Group_7__0");
			builder.put(grammarAccess.getAtomicTaskAccess().getGroup_8(), "rule__AtomicTask__Group_8__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup(), "rule__CompoundTask__Group__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_6(), "rule__CompoundTask__Group_6__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_8(), "rule__CompoundTask__Group_8__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_9(), "rule__CompoundTask__Group_9__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_10(), "rule__CompoundTask__Group_10__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_11(), "rule__CompoundTask__Group_11__0");
			builder.put(grammarAccess.getCompoundTaskAccess().getGroup_12(), "rule__CompoundTask__Group_12__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getLocationAccess().getGroup_8(), "rule__Location__Group_8__0");
			builder.put(grammarAccess.getPathsAccess().getGroup(), "rule__Paths__Group__0");
			builder.put(grammarAccess.getRobotsModelAccess().getGroup(), "rule__RobotsModel__Group__0");
			builder.put(grammarAccess.getCapabilityAccess().getGroup(), "rule__Capability__Group__0");
			builder.put(grammarAccess.getCapabilityAccess().getGroup_8(), "rule__Capability__Group_8__0");
			builder.put(grammarAccess.getCapabilityAccess().getGroup_9(), "rule__Capability__Group_9__0");
			builder.put(grammarAccess.getRobotAccess().getGroup(), "rule__Robot__Group__0");
			builder.put(grammarAccess.getRobotAccess().getGroup_14(), "rule__Robot__Group_14__0");
			builder.put(grammarAccess.getRobots2tasksPerformanceAccess().getGroup(), "rule__Robots2tasksPerformance__Group__0");
			builder.put(grammarAccess.getAtomicTaskNoLocAccess().getGroup(), "rule__AtomicTaskNoLoc__Group__0");
			builder.put(grammarAccess.getAtomicTaskNoLocAccess().getGroup_4(), "rule__AtomicTaskNoLoc__Group_4__0");
			builder.put(grammarAccess.getAtomicTaskLocAccess().getGroup(), "rule__AtomicTaskLoc__Group__0");
			builder.put(grammarAccess.getAtomicTaskLocAccess().getGroup_8(), "rule__AtomicTaskLoc__Group_8__0");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getGroup(), "rule__CompTaskNoLoc__Group__0");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getGroup_6(), "rule__CompTaskNoLoc__Group_6__0");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getGroup_7(), "rule__CompTaskNoLoc__Group_7__0");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getGroup(), "rule__CompTaskOneLoc__Group__0");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getGroup_8(), "rule__CompTaskOneLoc__Group_8__0");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getGroup_9(), "rule__CompTaskOneLoc__Group_9__0");
			builder.put(grammarAccess.getCompTaskListLocAccess().getGroup(), "rule__CompTaskListLoc__Group__0");
			builder.put(grammarAccess.getCompTaskListLocAccess().getGroup_9(), "rule__CompTaskListLoc__Group_9__0");
			builder.put(grammarAccess.getCompTaskListLocAccess().getGroup_11(), "rule__CompTaskListLoc__Group_11__0");
			builder.put(grammarAccess.getCompTaskListLocAccess().getGroup_12(), "rule__CompTaskListLoc__Group_12__0");
			builder.put(grammarAccess.getCompTaskAtButAccess().getGroup(), "rule__CompTaskAtBut__Group__0");
			builder.put(grammarAccess.getCompTaskAtButAccess().getGroup_11(), "rule__CompTaskAtBut__Group_11__0");
			builder.put(grammarAccess.getCompTaskAtButAccess().getGroup_13(), "rule__CompTaskAtBut__Group_13__0");
			builder.put(grammarAccess.getCompTaskAtButAccess().getGroup_14(), "rule__CompTaskAtBut__Group_14__0");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getGroup(), "rule__CompTaskStatedBut__Group__0");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getGroup_11(), "rule__CompTaskStatedBut__Group_11__0");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getGroup_13(), "rule__CompTaskStatedBut__Group_13__0");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getGroup_14(), "rule__CompTaskStatedBut__Group_14__0");
			builder.put(grammarAccess.getAllRobotsXXAccess().getGroup(), "rule__AllRobotsXX__Group__0");
			builder.put(grammarAccess.getAllRobotsXAccess().getGroup(), "rule__AllRobotsX__Group__0");
			builder.put(grammarAccess.getRobotsXXAccess().getGroup(), "rule__RobotsXX__Group__0");
			builder.put(grammarAccess.getRobotsXAccess().getGroup(), "rule__RobotsX__Group__0");
			builder.put(grammarAccess.getAllRobotsDeployAccess().getGroup(), "rule__AllRobotsDeploy__Group__0");
			builder.put(grammarAccess.getTimeAvailableAccess().getGroup(), "rule__TimeAvailable__Group__0");
			builder.put(grammarAccess.getNumAllocationsAccess().getGroup(), "rule__NumAllocations__Group__0");
			builder.put(grammarAccess.getNumPopulationAccess().getGroup(), "rule__NumPopulation__Group__0");
			builder.put(grammarAccess.getNumEvaluationsAccess().getGroup(), "rule__NumEvaluations__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getWorldModelAssignment_5(), "rule__ProblemSpecification__WorldModelAssignment_5");
			builder.put(grammarAccess.getProblemSpecificationAccess().getWorldModelAssignment_6(), "rule__ProblemSpecification__WorldModelAssignment_6");
			builder.put(grammarAccess.getProblemSpecificationAccess().getTasksModelAssignment_9(), "rule__ProblemSpecification__TasksModelAssignment_9");
			builder.put(grammarAccess.getProblemSpecificationAccess().getTasksModelAssignment_10(), "rule__ProblemSpecification__TasksModelAssignment_10");
			builder.put(grammarAccess.getProblemSpecificationAccess().getRobotsModelAssignment_13(), "rule__ProblemSpecification__RobotsModelAssignment_13");
			builder.put(grammarAccess.getProblemSpecificationAccess().getMissionAssignment_16(), "rule__ProblemSpecification__MissionAssignment_16");
			builder.put(grammarAccess.getProblemSpecificationAccess().getMissionAssignment_17(), "rule__ProblemSpecification__MissionAssignment_17");
			builder.put(grammarAccess.getProblemSpecificationAccess().getQosAssignment_18_0(), "rule__ProblemSpecification__QosAssignment_18_0");
			builder.put(grammarAccess.getProblemSpecificationAccess().getQosAssignment_18_1(), "rule__ProblemSpecification__QosAssignment_18_1");
			builder.put(grammarAccess.getAtomicTaskAccess().getNameAssignment_1(), "rule__AtomicTask__NameAssignment_1");
			builder.put(grammarAccess.getAtomicTaskAccess().getRobotsAssignment_3(), "rule__AtomicTask__RobotsAssignment_3");
			builder.put(grammarAccess.getAtomicTaskAccess().getLocAssignment_6_2(), "rule__AtomicTask__LocAssignment_6_2");
			builder.put(grammarAccess.getAtomicTaskAccess().getCriticalityAssignment_7_3(), "rule__AtomicTask__CriticalityAssignment_7_3");
			builder.put(grammarAccess.getAtomicTaskAccess().getDescriptionAssignment_8_3(), "rule__AtomicTask__DescriptionAssignment_8_3");
			builder.put(grammarAccess.getCompoundTaskAccess().getNameAssignment_1(), "rule__CompoundTask__NameAssignment_1");
			builder.put(grammarAccess.getCompoundTaskAccess().getCanDoTaskAssignment_5(), "rule__CompoundTask__CanDoTaskAssignment_5");
			builder.put(grammarAccess.getCompoundTaskAccess().getCanDoTaskAssignment_6_1(), "rule__CompoundTask__CanDoTaskAssignment_6_1");
			builder.put(grammarAccess.getCompoundTaskAccess().getLocationAssignment_8_1(), "rule__CompoundTask__LocationAssignment_8_1");
			builder.put(grammarAccess.getCompoundTaskAccess().getCriticalityAssignment_9_3(), "rule__CompoundTask__CriticalityAssignment_9_3");
			builder.put(grammarAccess.getCompoundTaskAccess().getOrderedAssignment_10_2(), "rule__CompoundTask__OrderedAssignment_10_2");
			builder.put(grammarAccess.getCompoundTaskAccess().getConsecutiveAssignment_11_2(), "rule__CompoundTask__ConsecutiveAssignment_11_2");
			builder.put(grammarAccess.getCompoundTaskAccess().getDescriptionAssignment_12_3(), "rule__CompoundTask__DescriptionAssignment_12_3");
			builder.put(grammarAccess.getLocationAccess().getNameAssignment_1(), "rule__Location__NameAssignment_1");
			builder.put(grammarAccess.getLocationAccess().getXAssignment_5(), "rule__Location__XAssignment_5");
			builder.put(grammarAccess.getLocationAccess().getYAssignment_7(), "rule__Location__YAssignment_7");
			builder.put(grammarAccess.getLocationAccess().getDescriptionAssignment_8_1(), "rule__Location__DescriptionAssignment_8_1");
			builder.put(grammarAccess.getPathsAccess().getLoc1Assignment_1(), "rule__Paths__Loc1Assignment_1");
			builder.put(grammarAccess.getPathsAccess().getLoc2Assignment_3(), "rule__Paths__Loc2Assignment_3");
			builder.put(grammarAccess.getPathsAccess().getDistanceAssignment_6(), "rule__Paths__DistanceAssignment_6");
			builder.put(grammarAccess.getRobotsModelAccess().getRobotsAssignment_2(), "rule__RobotsModel__RobotsAssignment_2");
			builder.put(grammarAccess.getRobotsModelAccess().getRobotsAssignment_3(), "rule__RobotsModel__RobotsAssignment_3");
			builder.put(grammarAccess.getCapabilityAccess().getNameAssignment_1(), "rule__Capability__NameAssignment_1");
			builder.put(grammarAccess.getCapabilityAccess().getAtAssignment_7(), "rule__Capability__AtAssignment_7");
			builder.put(grammarAccess.getCapabilityAccess().getAtAssignment_8_1(), "rule__Capability__AtAssignment_8_1");
			builder.put(grammarAccess.getCapabilityAccess().getDescriptionAssignment_9_1(), "rule__Capability__DescriptionAssignment_9_1");
			builder.put(grammarAccess.getRobotAccess().getNameAssignment_1(), "rule__Robot__NameAssignment_1");
			builder.put(grammarAccess.getRobotAccess().getInitLocAssignment_6(), "rule__Robot__InitLocAssignment_6");
			builder.put(grammarAccess.getRobotAccess().getVelocityAssignment_9(), "rule__Robot__VelocityAssignment_9");
			builder.put(grammarAccess.getRobotAccess().getRobots2tasksPerformanceAssignment_13(), "rule__Robot__Robots2tasksPerformanceAssignment_13");
			builder.put(grammarAccess.getRobotAccess().getRobots2tasksPerformanceAssignment_14_1(), "rule__Robot__Robots2tasksPerformanceAssignment_14_1");
			builder.put(grammarAccess.getRobots2tasksPerformanceAccess().getAtAssignment_1(), "rule__Robots2tasksPerformance__AtAssignment_1");
			builder.put(grammarAccess.getRobots2tasksPerformanceAccess().getTimeAssignment_5(), "rule__Robots2tasksPerformance__TimeAssignment_5");
			builder.put(grammarAccess.getRobots2tasksPerformanceAccess().getProbAssignment_10(), "rule__Robots2tasksPerformance__ProbAssignment_10");
			builder.put(grammarAccess.getAtomicTaskNoLocAccess().getNameAssignment_1(), "rule__AtomicTaskNoLoc__NameAssignment_1");
			builder.put(grammarAccess.getAtomicTaskNoLocAccess().getAtAssignment_3(), "rule__AtomicTaskNoLoc__AtAssignment_3");
			builder.put(grammarAccess.getAtomicTaskNoLocAccess().getDescriptionAssignment_4_1(), "rule__AtomicTaskNoLoc__DescriptionAssignment_4_1");
			builder.put(grammarAccess.getAtomicTaskLocAccess().getNameAssignment_1(), "rule__AtomicTaskLoc__NameAssignment_1");
			builder.put(grammarAccess.getAtomicTaskLocAccess().getAtAssignment_5(), "rule__AtomicTaskLoc__AtAssignment_5");
			builder.put(grammarAccess.getAtomicTaskLocAccess().getLocAssignment_7(), "rule__AtomicTaskLoc__LocAssignment_7");
			builder.put(grammarAccess.getAtomicTaskLocAccess().getDescriptionAssignment_8_1(), "rule__AtomicTaskLoc__DescriptionAssignment_8_1");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getNameAssignment_1(), "rule__CompTaskNoLoc__NameAssignment_1");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getCtAssignment_5(), "rule__CompTaskNoLoc__CtAssignment_5");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getCriticalityAssignment_6_2(), "rule__CompTaskNoLoc__CriticalityAssignment_6_2");
			builder.put(grammarAccess.getCompTaskNoLocAccess().getDescriptionAssignment_7_1(), "rule__CompTaskNoLoc__DescriptionAssignment_7_1");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getNameAssignment_1(), "rule__CompTaskOneLoc__NameAssignment_1");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getCtAssignment_5(), "rule__CompTaskOneLoc__CtAssignment_5");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getLocAssignment_7(), "rule__CompTaskOneLoc__LocAssignment_7");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getCriticalityAssignment_8_2(), "rule__CompTaskOneLoc__CriticalityAssignment_8_2");
			builder.put(grammarAccess.getCompTaskOneLocAccess().getDescriptionAssignment_9_1(), "rule__CompTaskOneLoc__DescriptionAssignment_9_1");
			builder.put(grammarAccess.getCompTaskListLocAccess().getNameAssignment_1(), "rule__CompTaskListLoc__NameAssignment_1");
			builder.put(grammarAccess.getCompTaskListLocAccess().getCtAssignment_5(), "rule__CompTaskListLoc__CtAssignment_5");
			builder.put(grammarAccess.getCompTaskListLocAccess().getLocationListAssignment_8(), "rule__CompTaskListLoc__LocationListAssignment_8");
			builder.put(grammarAccess.getCompTaskListLocAccess().getLocationListAssignment_9_1(), "rule__CompTaskListLoc__LocationListAssignment_9_1");
			builder.put(grammarAccess.getCompTaskListLocAccess().getCriticalityAssignment_11_2(), "rule__CompTaskListLoc__CriticalityAssignment_11_2");
			builder.put(grammarAccess.getCompTaskListLocAccess().getDescriptionAssignment_12_1(), "rule__CompTaskListLoc__DescriptionAssignment_12_1");
			builder.put(grammarAccess.getCompTaskAtButAccess().getNameAssignment_1(), "rule__CompTaskAtBut__NameAssignment_1");
			builder.put(grammarAccess.getCompTaskAtButAccess().getCtAssignment_5(), "rule__CompTaskAtBut__CtAssignment_5");
			builder.put(grammarAccess.getCompTaskAtButAccess().getLocAssignment_7(), "rule__CompTaskAtBut__LocAssignment_7");
			builder.put(grammarAccess.getCompTaskAtButAccess().getLocationListAssignment_10(), "rule__CompTaskAtBut__LocationListAssignment_10");
			builder.put(grammarAccess.getCompTaskAtButAccess().getLocationListAssignment_11_1(), "rule__CompTaskAtBut__LocationListAssignment_11_1");
			builder.put(grammarAccess.getCompTaskAtButAccess().getCriticalityAssignment_13_2(), "rule__CompTaskAtBut__CriticalityAssignment_13_2");
			builder.put(grammarAccess.getCompTaskAtButAccess().getDescriptionAssignment_14_1(), "rule__CompTaskAtBut__DescriptionAssignment_14_1");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getNameAssignment_1(), "rule__CompTaskStatedBut__NameAssignment_1");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getCtAssignment_5(), "rule__CompTaskStatedBut__CtAssignment_5");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getLocationListAssignment_10(), "rule__CompTaskStatedBut__LocationListAssignment_10");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getLocationListAssignment_11_1(), "rule__CompTaskStatedBut__LocationListAssignment_11_1");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getCriticalityAssignment_13_2(), "rule__CompTaskStatedBut__CriticalityAssignment_13_2");
			builder.put(grammarAccess.getCompTaskStatedButAccess().getDescriptionAssignment_14_1(), "rule__CompTaskStatedBut__DescriptionAssignment_14_1");
			builder.put(grammarAccess.getAllRobotsXXAccess().getCoordinateAssignment_5(), "rule__AllRobotsXX__CoordinateAssignment_5");
			builder.put(grammarAccess.getAllRobotsXXAccess().getXy1Assignment_7(), "rule__AllRobotsXX__Xy1Assignment_7");
			builder.put(grammarAccess.getAllRobotsXXAccess().getXy2Assignment_9(), "rule__AllRobotsXX__Xy2Assignment_9");
			builder.put(grammarAccess.getAllRobotsXAccess().getCoordinateAssignment_2(), "rule__AllRobotsX__CoordinateAssignment_2");
			builder.put(grammarAccess.getAllRobotsXAccess().getTypeAssignment_3(), "rule__AllRobotsX__TypeAssignment_3");
			builder.put(grammarAccess.getAllRobotsXAccess().getXyAssignment_4(), "rule__AllRobotsX__XyAssignment_4");
			builder.put(grammarAccess.getRobotsXXAccess().getRobotAssignment_2(), "rule__RobotsXX__RobotAssignment_2");
			builder.put(grammarAccess.getRobotsXXAccess().getCoordinateAssignment_4(), "rule__RobotsXX__CoordinateAssignment_4");
			builder.put(grammarAccess.getRobotsXXAccess().getXy1Assignment_6(), "rule__RobotsXX__Xy1Assignment_6");
			builder.put(grammarAccess.getRobotsXXAccess().getXy2Assignment_8(), "rule__RobotsXX__Xy2Assignment_8");
			builder.put(grammarAccess.getRobotsXAccess().getRobotAssignment_2(), "rule__RobotsX__RobotAssignment_2");
			builder.put(grammarAccess.getRobotsXAccess().getCoordinateAssignment_4(), "rule__RobotsX__CoordinateAssignment_4");
			builder.put(grammarAccess.getRobotsXAccess().getTypeAssignment_5(), "rule__RobotsX__TypeAssignment_5");
			builder.put(grammarAccess.getRobotsXAccess().getXyAssignment_6(), "rule__RobotsX__XyAssignment_6");
			builder.put(grammarAccess.getTimeAvailableAccess().getNumberAssignment_2(), "rule__TimeAvailable__NumberAssignment_2");
			builder.put(grammarAccess.getNumAllocationsAccess().getNumberAssignment_2(), "rule__NumAllocations__NumberAssignment_2");
			builder.put(grammarAccess.getNumPopulationAccess().getNumberAssignment_2(), "rule__NumPopulation__NumberAssignment_2");
			builder.put(grammarAccess.getNumEvaluationsAccess().getNumberAssignment_2(), "rule__NumEvaluations__NumberAssignment_2");
			builder.put(grammarAccess.getLocationOrSpaceAccess().getSpaceAssignment_0(), "rule__LocationOrSpace__SpaceAssignment_0");
			builder.put(grammarAccess.getLocationOrSpaceAccess().getLocAssignment_1(), "rule__LocationOrSpace__LocAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
